# Generated by Django 5.2.8 on 2025-11-28 20:52

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_article_pub_date_alter_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=tinymce.models.HTMLField(),
        ),
    ]
